_target_: setbench.tasks.regex.RegexTask
task_name: regex_4
regex_list:
  - "(?=AV)"
  - "(?=VC)"
  - "(?=CA)"
  - "(?=AY)"
obj_dim: 4
log_prefix: regex
min_len: 32
max_len: 36
num_start_examples: 512
batch_size: 16
max_num_edits: 1
max_ngram_size: 1
allow_len_change: True
max_score_per_dim: 18