_target_: setbench.optimizers.lambo.LaMBO
_recursive_: False
num_rounds: 64
num_gens: 256
num_opt_steps: 32
patience: 32
lr: 0.1
mask_ratio: 0.125
resampling_weight: 1.
encoder_obj: mlm
optimize_latent: True
position_sampler: uniform
entropy_penalty: 1e-2
window_size: 1