_target_: setbench.algorithms.rand_hill.RandHill
_recursive_: False
max_len: ${task.max_len}
min_len: ${task.min_len}
train_steps: 20000
max_size: 50
eval_metrics: ["hypervolume"]
state_save_path: "/home/deokjae/setbench/results_table1/"